title: "Camilo Alberto Cárdenas Hurtado"
author: "Camilo Cárdenas-Hurtado"
description: "London School of Economics and Political Science"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {title: "Research", file: "Research.md"}
  - {title: "Teaching", file: "Teaching.md"}
  - {title: "CV", file: "ccardehu_CV_May2023.pdf"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:c.a.cardenas-hurtado@lse.ac.uk"}
  - {title: Github, icon: github, url: "https://github.com/ccardehu"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/ccardehu"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/ccardehu"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
