title: "SWANSCODEX"
author: "Soowan Choi"
description: "---"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: 'Home', icon: home}
  #- {file: "README.md", title: 'About Me'}
  - {file: "explore.md", title: 'ML Projects'}
  - {file: "ssm.md", title: 'Thoughts'}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:soowan.choi@queensu.ca"}
  - {title: Github, icon: github, url: "https://github.com/swanscodex"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
