title: "James Mejia's Blog"
author: "James Mejia"
description: "From CÃºcuta to the world"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", "Home Change", icon: home }
  - {file: "README.md", title: "About me", icon: address-card }

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:contacto@jamesmejia.me"}
  - {title: Github, icon: github, url: "https://github.com/codingjhames"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/CodingJhames"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
