title: "LEARNING MADE EASY"
author: "Blog Author"
description: "E Learning system using cloud computing"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html",title: "Home", icon: "Home"}
  - {title: "Faculty", sidebaricon: "Faculty",icon: "Faculty"}
  - {title: "Student", sidebar: "student"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "julvancesonwa64@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Easylearningmade"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
