title: "Blog Title"
author: "Blog Author"
description: "Really cool blog about ... something"
more: "read more Â»"
url: "https://niklasbuschmann.github.io/"
baseurl: "/contrast"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - about.md
  - archive.html

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/me/"
  - github: "https://github.com/me/"
  - envelope: "mailto:me@example.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
