# Setup
title:            Chris F. Nicholson
tagline:          'A place for the things I enjoy.'
description:      'Recipes and some writings by Chris F. Nicholson'
url:              https://www.chrisfnicholson.com
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Chris F. Nicholson'
  url:            https://www.chrisfnicholson.com

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Layout

show_social: false          # show site description and social links in the footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Theme
style: default
# dark_theme: true
# dark_nav: true

# Menu
navigation:
#  - {title: Home, file: "index.html", icon: home}
  - {title: Recipes, icon: utensils, url: "/recipes/"}
  - {title: Cocktails, icon: glass-martini-alt, url: "/drinks/"}
  - {title: Crosswords, icon: crossword, url: "crosswords.html"}

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-datapage-generator
#  - jekyll-responsive-image
  - jekyll-webp
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-pwa-workbox

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore
  - vendor
  - Pipfile
  - package.json

page_gen:
  - data: recipes
    template: recipe
    name: name
    dir: recipes
    extension: html

  - data: puzzles
    template: crossword
    name: name
    dir: crosswords
    extension: html

  - data: drinks
    template: drink
    name: name
    title: name
    dir: drinks
    extension: html

# responsive_image:
#  template: _includes/responsive-image.html
#  base_path: assets
#  sizes:
#    - width: 320
#    - width: 480
#    - width: 800

pwa:
  enabled: true # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: /js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{js,json,css}"
    - "/assets/images/recipes/*.{ico,png,svg,webp}"
#    - "/assets/images/drinks/*.{ico,png,svg,webp}"
    - "/recipes/*.html"
    - "/drinks/*.html"
    - "/index.html"
  precache_glob_ignores: # Optional
    - "sw-register.js"
    - "fonts/**/*"

staticman_url: https://chrisfnicholson-staticman.herokuapp.com/v2/entry/datapolitical/chrisfnicholson.github.io/main/comments

siteKey: 6Ld6YHkaAAAAADYH6TZFvNMjTBnZa7NCSIZMlRQ_
secret: oIWqlCzkykNTc4xd+MBjVRjWUHqcn99OiOfOV53swm8yksTwYDAiP+3duj63LVrMPZJ/fLFunVjAqyG3C9PTHM3qz2hnxhWg36hmU5B401oMsHcFX6+Q1tCqJ3sbdvKe2OnaTl6gIyh+vwyltVyxFy3Rj7Rn9wX2spw13vyIEE5vgA9y/7qNDiSO52esH5FPFV1gD6/4WPZDtHjTH9+H9wja4Jxva0nCtZ8iQvjYnxzZXRBiz8BhTDdjH54cM2Ok9mjTxvzvsv9nsQSmmm3DfVvYvXFAfGIAN4fNFpa7G/7dKBX7HKD5/NUqfvBtzSn06NaGgey36BCEb5pKgfcPBrMOybmZK1jqobsApZ6ob4umQiFIWiW8eBv5JrLQisROrhB6+ZivD7PKGjRiTJmybTJ/gHNFMO9owv/WGop3XUy+WS3BcTnN2MtxPgSrhYTPTriL2NnB8O834009W2KbyjmmEqi7R0ZmPnAPxtqZ/YBu7/JVqe3eEKARBIHFy6XeMij7FXtz36ihcJj5lZFrQ6t6YJHg+Qw+21azZjjVurnpMMrPjsdLRTZAe82nSPYH3cixDUnIzm1vnKjMRhNnqiD/Lj4K6C6FV/U+VIyVlGTtN0rWE23P1tluAzG5Zsn4yWxmxwSDbHjGzqMniWz8kL2lv6rSfIqPqKEVs+YXsEw=


############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["assets/images/recipes", "assets/images/drinks"]

  # Whether to search in nested directories or not
  nested: no

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################
