title: "TRANSLOC"
author: "Transloc"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
    - {file: "aboutTL.md" , title: "About the Project"}
    - {file: "blog.md" , title: "BLOG"}
    - {file: "index.html" , title: "TransLoc Home Page", icon : home}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {file: "aboutTL.md" , title: "About the Project"}
  - {title: Mail, icon: envelope, url: "mailto:linda.angulo-lopez@mnhn.fr"}
  - {title: Github, icon: github, url: "https://github.com/ConservationTranslocation"}
  - {file: "index.html" , title: "TransLoc Home Page", icon : home}
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
