title: "Betty A. Onyango"
author: "Bett A. Onyango"
description: "University Canada West"
permalink: /:categories/:year/:month/:day/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "About", url: "/about/", icon: user}
  - {title: "Blog", url: "/blog/", icon: pencil-alt}
  - {title: "CV", url: "Bettys cv updated.pdf", icon: file-alt}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Gmail, icon: envelope, url: "mailto:onyango2betty@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Betty-coded"}
  - {title: Linkedin, icon: linkedin, url: "www.linkedin.com/in/betty-onyango-8765612a5"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/pinkharlem?igsh=bjBidGo1YTIxdDYy"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-seo-tag

 ##include folders
 include:
  -posts
  -assets
