title: "Blog Title"
author: "Blog Author"
description: "Really cool blog about ... something"
permalink: /:title/
lang: "en"

dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark
dark_theme: false            # use the dark mode as default
show_footer: false           # show the "previous" and "next" links at the end of each post
hide_title: false            # don't show the site title in the header
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - README.md
  - Github: "http://github.com/niklasbuschmann/contrast"

#icons:                      # icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
#  github: "https://github.com/niklasbuschmann/contrast"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
