title: "Blog Title"
author: "Blog Author"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}

external:                  # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
