title: "Nob1eChA0z"
author: "NobleChA0z"
description: "Game Highlights"
permalink: /:title/ 
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                
  - {file: "index.html", title: "Home", icon: home}
  - {file: "README.md", title: "About me", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:noblechaos@icloud.com"}
  - {title: Github, icon: github, url: "https://github.com/Nob1eCha0z"}
  - {title: Facebook, icon: facebook, url: "https://m.facebook.com/willie.lamb.32"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
