title: "Lukas Delgado-Prieto"
author: ""
description: "Universidad Carlos III de Madrid"
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "home.md" , title: "Home"}
  - {file: "research.md" , title: "Research"}
  - {file: "teaching.md" , title: "Teaching"}
  - {file: "blog.md" , title: "Blog"}
  - {file: "resources.md" , title: "Resources"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ludelgad@eco.uc3m.es"}
  - {title: Github, icon: github, url: "https://github.com/ludelgad"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/LaDelgadoP"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
