title: "Blog Title"
author: "Blog Author"
description: "Really cool blog about ... something"
permalink: /:title/
lang: "en"

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_footer: false           # show the "previous" and "next" links at the end of each post
dark_header: false           # keep the top-header dark
hide_title: false            # hide the site title in the header
minimal: false               # minima-inspired style without box-shadows

# see http://fontawesome.com/icons for icons

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}

external:
  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
